/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package fot;

/**
 *
 * @author user
 */
public class Admin_Interface extends javax.swing.JFrame {

    /** Creates new form Admin_Interface */
    public Admin_Interface() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adminNotice = new javax.swing.JLabel();
        adminProfile = new javax.swing.JLabel();
        adminCourse = new javax.swing.JLabel();
        adminTime = new javax.swing.JLabel();
        adminTxt = new javax.swing.JLabel();
        AdminTxt = new javax.swing.JLabel();
        courseTxt = new javax.swing.JLabel();
        noticeTxt = new javax.swing.JLabel();
        timetableTxt = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        backImg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Interface");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        adminNotice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/notice1.png"))); // NOI18N
        adminNotice.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        adminNotice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminNoticeMouseClicked(evt);
            }
        });
        getContentPane().add(adminNotice, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 130, 120));

        adminProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Update1.png"))); // NOI18N
        adminProfile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        adminProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminProfileMouseClicked(evt);
            }
        });
        getContentPane().add(adminProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 130, 120));

        adminCourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/course1.png"))); // NOI18N
        adminCourse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        adminCourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminCourseMouseClicked(evt);
            }
        });
        getContentPane().add(adminCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, 130, 120));

        adminTime.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/time1.png"))); // NOI18N
        adminTime.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        adminTime.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminTimeMouseClicked(evt);
            }
        });
        getContentPane().add(adminTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 320, 130, 120));

        adminTxt.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        adminTxt.setForeground(new java.awt.Color(255, 255, 255));
        adminTxt.setText("Welcome To Admin");
        getContentPane().add(adminTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, -1));

        AdminTxt.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        AdminTxt.setForeground(new java.awt.Color(255, 255, 255));
        AdminTxt.setText("Create & Maintain Profiles");
        AdminTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        AdminTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdminTxtMouseClicked(evt);
            }
        });
        getContentPane().add(AdminTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, -1, -1));

        courseTxt.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        courseTxt.setForeground(new java.awt.Color(255, 255, 255));
        courseTxt.setText("Create & Maintain Courses");
        courseTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        courseTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                courseTxtMouseClicked(evt);
            }
        });
        getContentPane().add(courseTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, -1, -1));

        noticeTxt.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        noticeTxt.setForeground(new java.awt.Color(255, 255, 255));
        noticeTxt.setText("Create & Maintain TimeTables");
        noticeTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        noticeTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                noticeTxtMouseClicked(evt);
            }
        });
        getContentPane().add(noticeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 450, -1, -1));

        timetableTxt.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        timetableTxt.setForeground(new java.awt.Color(255, 255, 255));
        timetableTxt.setText("Create & Maintain Notices");
        timetableTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        timetableTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                timetableTxtMouseClicked(evt);
            }
        });
        getContentPane().add(timetableTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, -1, -1));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logout.png"))); // NOI18N
        jLabel25.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel25MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 30, 50, 50));

        backImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/profBack.jpg"))); // NOI18N
        getContentPane().add(backImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AdminTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminTxtMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminTxtMouseClicked

    private void courseTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_courseTxtMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_courseTxtMouseClicked

    private void noticeTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noticeTxtMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_noticeTxtMouseClicked

    private void timetableTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timetableTxtMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_timetableTxtMouseClicked

    private void adminCourseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminCourseMouseClicked
        Admin_Course course=new Admin_Course();
        course.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_adminCourseMouseClicked

    private void adminNoticeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminNoticeMouseClicked

        Admin_Notice notice=new Admin_Notice();
        notice.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_adminNoticeMouseClicked

    private void adminProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminProfileMouseClicked
       Admin_Profile pro=new Admin_Profile();
        pro.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_adminProfileMouseClicked

    private void adminTimeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminTimeMouseClicked
        Admin_TimeTable time=new Admin_TimeTable();
        time.setVisible(true);
        this.setVisible(false);        
    }//GEN-LAST:event_adminTimeMouseClicked

    private void jLabel25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseClicked
        form_Admin fm=new form_Admin();
        fm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel25MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdminTxt;
    private javax.swing.JLabel adminCourse;
    private javax.swing.JLabel adminNotice;
    private javax.swing.JLabel adminProfile;
    private javax.swing.JLabel adminTime;
    private javax.swing.JLabel adminTxt;
    private javax.swing.JLabel backImg;
    private javax.swing.JLabel courseTxt;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel noticeTxt;
    private javax.swing.JLabel timetableTxt;
    // End of variables declaration//GEN-END:variables

}
