/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fot;

/**
 *
 * @author user
 */
public class Admin_Notice extends javax.swing.JFrame {

    /**
     * Creates new form Admin_Notice
     */
    public Admin_Notice() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewNotice = new javax.swing.JLabel();
        deleteNotice = new javax.swing.JLabel();
        createNotice = new javax.swing.JLabel();
        editNotice1 = new javax.swing.JLabel();
        createTxt = new javax.swing.JLabel();
        editTxt = new javax.swing.JLabel();
        deleteTxt = new javax.swing.JLabel();
        NoticeExit = new javax.swing.JLabel();
        ViewNotice = new javax.swing.JLabel();
        viewTxt = new javax.swing.JLabel();
        noticeBackImg = new javax.swing.JLabel();

        viewNotice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/deleteNotice.png"))); // NOI18N
        viewNotice.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewNotice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewNoticeMouseClicked(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Create & Maintaine Notice");
        setFocusable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        deleteNotice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/deleteNotice.png"))); // NOI18N
        deleteNotice.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteNotice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteNoticeMouseClicked(evt);
            }
        });
        getContentPane().add(deleteNotice, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 50, 50));

        createNotice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/createNotice.png"))); // NOI18N
        createNotice.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createNotice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createNoticeMouseClicked(evt);
            }
        });
        getContentPane().add(createNotice, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 50, 50));

        editNotice1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/editNotice.png"))); // NOI18N
        editNotice1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editNotice1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editNotice1MouseClicked(evt);
            }
        });
        getContentPane().add(editNotice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 50, 50));

        createTxt.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        createTxt.setForeground(new java.awt.Color(255, 255, 255));
        createTxt.setText("Create Notice");
        createTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createTxtMouseClicked(evt);
            }
        });
        getContentPane().add(createTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, -1, -1));

        editTxt.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        editTxt.setForeground(new java.awt.Color(255, 255, 255));
        editTxt.setText("Edit Notice");
        editTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editTxtMouseClicked(evt);
            }
        });
        getContentPane().add(editTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, -1, -1));

        deleteTxt.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        deleteTxt.setForeground(new java.awt.Color(255, 255, 255));
        deleteTxt.setText("Delete Notice");
        deleteTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteTxtMouseClicked(evt);
            }
        });
        getContentPane().add(deleteTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, -1, -1));

        NoticeExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/exit.png"))); // NOI18N
        NoticeExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        NoticeExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NoticeExitMouseClicked(evt);
            }
        });
        getContentPane().add(NoticeExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        ViewNotice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/viewTimetable.png"))); // NOI18N
        ViewNotice.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ViewNotice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewNoticeMouseClicked(evt);
            }
        });
        getContentPane().add(ViewNotice, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 50, 50));

        viewTxt.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        viewTxt.setForeground(new java.awt.Color(255, 255, 255));
        viewTxt.setText("View Notice");
        viewTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewTxtMouseClicked(evt);
            }
        });
        getContentPane().add(viewTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, -1, -1));

        noticeBackImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/profBack.jpg"))); // NOI18N
        getContentPane().add(noticeBackImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void NoticeExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NoticeExitMouseClicked
       Admin_Interface inter=new Admin_Interface();  // back to the user profiles
        inter.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_NoticeExitMouseClicked

    private void createNoticeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createNoticeMouseClicked
        Create_Notice cNotice=new Create_Notice();  
        cNotice.setVisible(true);
        this.setVisible(false);  
    }//GEN-LAST:event_createNoticeMouseClicked

    private void createTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createTxtMouseClicked
        Create_Notice cNotice=new Create_Notice();  
        cNotice.setVisible(true);
        this.setVisible(false);       
    }//GEN-LAST:event_createTxtMouseClicked

    private void editNotice1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editNotice1MouseClicked
      Edit_Notice eNotice=new Edit_Notice();  
      eNotice.setVisible(true);
      this.setVisible(false);   
    }//GEN-LAST:event_editNotice1MouseClicked

    private void editTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editTxtMouseClicked
      Edit_Notice eNotice=new Edit_Notice();  
      eNotice.setVisible(true);
      this.setVisible(false); 
    }//GEN-LAST:event_editTxtMouseClicked

    private void deleteNoticeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteNoticeMouseClicked
        Delete_Notice dNotice=new Delete_Notice();  
        dNotice.setVisible(true);
        this.setVisible(false);          
    }//GEN-LAST:event_deleteNoticeMouseClicked

    private void deleteTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteTxtMouseClicked
        Delete_Notice dNotice=new Delete_Notice();  
        dNotice.setVisible(true);
        this.setVisible(false);       
    }//GEN-LAST:event_deleteTxtMouseClicked

    private void viewNoticeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewNoticeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_viewNoticeMouseClicked

    private void ViewNoticeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewNoticeMouseClicked
       View_Notice vNotice=new View_Notice();  
        vNotice.setVisible(true);
        this.setVisible(false);   
    }//GEN-LAST:event_ViewNoticeMouseClicked

    private void viewTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewTxtMouseClicked
        View_Notice vNotice=new View_Notice();  
        vNotice.setVisible(true);
        this.setVisible(false); 
    }//GEN-LAST:event_viewTxtMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Notice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Notice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Notice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Notice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_Notice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NoticeExit;
    private javax.swing.JLabel ViewNotice;
    private javax.swing.JLabel createNotice;
    private javax.swing.JLabel createTxt;
    private javax.swing.JLabel deleteNotice;
    private javax.swing.JLabel deleteTxt;
    private javax.swing.JLabel editNotice1;
    private javax.swing.JLabel editTxt;
    private javax.swing.JLabel noticeBackImg;
    private javax.swing.JLabel viewNotice;
    private javax.swing.JLabel viewTxt;
    // End of variables declaration//GEN-END:variables
}
