package fot;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MINHA
 */
public class Att extends javax.swing.JFrame {
            Connection con=null;
            ResultSet rs=null;
            PreparedStatement pst;
    /**
     * Creates new form Attendance
     */
    public  Att() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        subIdTxt = new javax.swing.JTextField();
        stuIdTxt = new javax.swing.JTextField();
        subId = new javax.swing.JLabel();
        stuId = new javax.swing.JLabel();
        day = new javax.swing.JLabel();
        dayTxt = new javax.swing.JTextField();
        type = new javax.swing.JLabel();
        Exit = new javax.swing.JLabel();
        hoursTxt = new javax.swing.JTextField();
        hours = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        typeTxt = new javax.swing.JTextField();
        statusTxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        editSearch = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Modify Attendance Details");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        subIdTxt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        getContentPane().add(subIdTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 150, 30));

        stuIdTxt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        getContentPane().add(stuIdTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 150, -1));

        subId.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        subId.setForeground(new java.awt.Color(204, 204, 0));
        subId.setText("Subject ID");
        getContentPane().add(subId, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        stuId.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        stuId.setForeground(new java.awt.Color(204, 204, 0));
        stuId.setText("Student ID");
        getContentPane().add(stuId, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        day.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        day.setForeground(new java.awt.Color(204, 204, 0));
        day.setText("Day");
        getContentPane().add(day, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        dayTxt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        getContentPane().add(dayTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 150, 30));

        type.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        type.setForeground(new java.awt.Color(255, 255, 255));
        type.setText("Type");
        getContentPane().add(type, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/exit.png"))); // NOI18N
        Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });
        getContentPane().add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, -1, -1));

        hoursTxt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        getContentPane().add(hoursTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 150, -1));

        hours.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        hours.setForeground(new java.awt.Color(255, 255, 255));
        hours.setText("Hours");
        getContentPane().add(hours, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 50, -1));

        status.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        status.setForeground(new java.awt.Color(255, 255, 255));
        status.setText("Status");
        getContentPane().add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, -1, -1));

        typeTxt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        getContentPane().add(typeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 150, 30));

        statusTxt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        getContentPane().add(statusTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, 150, 30));

        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, 70, -1));

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, -1, -1));

        editSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search.png"))); // NOI18N
        editSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editSearchMouseClicked(evt);
            }
        });
        getContentPane().add(editSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 30, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/interface1.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setPreferredSize(new java.awt.Dimension(600, 500));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        Attendance_TO co=new Attendance_TO();
        co.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ExitMouseClicked

    private void editSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editSearchMouseClicked
        tec_att to=new tec_att();
        
        String id=stuIdTxt.getText();
        String sub=subIdTxt.getText();
        String day=dayTxt.getText();
        
        if(!id.isEmpty() && !sub.isEmpty() && !day.isEmpty())
        {
            ResultSet rs=to.searchAtt(id,sub,day);
            try {
                if(rs.next())
                {
                   typeTxt.setText(rs.getString("type"));
                   hoursTxt.setText(rs.getString("hours"));
                   statusTxt.setText(rs.getString("status"));
                }
                else
                {
                     javax.swing.JOptionPane.showMessageDialog(null, "Data not in the database");
                     clear();
                }
            } 
            catch (Exception ex) {
                JOptionPane.showMessageDialog(null,"error....");
            } 
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Please enter student id, subject id and day");
        }
    }//GEN-LAST:event_editSearchMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         tec_att to=new tec_att();
       
       to.setId(stuIdTxt.getText());
       to.setSub(subIdTxt.getText());
       to.setDay(dayTxt.getText());
       to.setType(typeTxt.getText());
       to.setHours(hoursTxt.getText());
       to.setStatus(statusTxt.getText());
            
       to.edit();

       clear();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         tec_att to=new tec_att();
       
       to.setId(stuIdTxt.getText());
       to.setSub(subIdTxt.getText());
       to.setDay(dayTxt.getText());
       to.setType(typeTxt.getText());
       to.setHours(hoursTxt.getText());
       to.setStatus(statusTxt.getText());
            
       to.delete();

       clear();
    }//GEN-LAST:event_jButton1ActionPerformed
 
    
    public void clear(){
        stuIdTxt.setText("");
        subIdTxt.setText("");
        hoursTxt.setText("");
        statusTxt.setText("");
        typeTxt.setText("");
        dayTxt.setText("");
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Att.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
      //</editor-fold>
      //</editor-fold>
      
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new  Att().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Exit;
    private javax.swing.JLabel day;
    private javax.swing.JTextField dayTxt;
    private javax.swing.JLabel editSearch;
    private javax.swing.JLabel hours;
    private javax.swing.JTextField hoursTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel status;
    private javax.swing.JTextField statusTxt;
    private javax.swing.JLabel stuId;
    private javax.swing.JTextField stuIdTxt;
    private javax.swing.JLabel subId;
    private javax.swing.JTextField subIdTxt;
    private javax.swing.JLabel type;
    private javax.swing.JTextField typeTxt;
    // End of variables declaration//GEN-END:variables
}
