/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fot;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Ishanka
 */
public class attendance extends javax.swing.JFrame {

    /**
     * Creates new form attendance
     */
    Student stu=new Student();
    public attendance() {
        initComponents();
        showAtt2();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pra = new javax.swing.JLabel();
        theory = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        att = new javax.swing.JLabel();
        attCount = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        praCount = new javax.swing.JLabel();
        stuBar = new javax.swing.JPanel();
        sub_code = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        atttble = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("View Attendance Details");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/exit.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 40, 30, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("See Attendance ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 200, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/att1.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 120, 130));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search.png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, 30, 30));

        jLabel6.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setText("---Eligibility ---");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 130, 30));

        pra.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        pra.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(pra, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 400, 80, 20));

        theory.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        theory.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(theory, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, 80, -1));

        jLabel9.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 0));
        jLabel9.setText("Practical");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, 80, -1));

        att.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        att.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(att, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 370, 80, 20));

        attCount.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        attCount.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(attCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, 80, 20));

        jLabel8.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 0));
        jLabel8.setText("Attendance");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, 80, -1));

        praCount.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        praCount.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(praCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, 80, 20));

        stuBar.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout stuBarLayout = new javax.swing.GroupLayout(stuBar);
        stuBar.setLayout(stuBarLayout);
        stuBarLayout.setHorizontalGroup(
            stuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        stuBarLayout.setVerticalGroup(
            stuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(stuBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 5, 100));

        sub_code.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sub_codeMouseClicked(evt);
            }
        });
        sub_code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub_codeActionPerformed(evt);
            }
        });
        getContentPane().add(sub_code, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 130, -1));

        atttble.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        jScrollPane2.setViewportView(atttble);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 630, 130));

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Subject Code");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/profBack.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 450));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        stu1 stu=new stu1();
        stu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void sub_codeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub_codeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sub_codeActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked


        String sub=sub_code.getText();
        if(!sub.equals("")){
            try {
                Connection con=MyConnection.getConnection();
                String sql="select * from attendance where stu_id='"+stu.getRegno()+"' AND sub_id='"+sub+"'";
                PreparedStatement ps=con.prepareStatement(sql);
                ResultSet rs=ps.executeQuery();
                atttble.setModel(DbUtils.resultSetToTableModel(rs));
                atttble.setVisible(true);
                
                if(!sub.equals("TCS2112"))
                {
                    eligibility();
                }
                
                 if(sub.equals("TCS2112"))
                {
                    eligibility_TCS();
                }
                
            } catch (Exception e) {
                atttble.setVisible(false);
            }
        }
        else
        {
            atttble.setVisible(false);
            JOptionPane.showMessageDialog(null,"Please enter subject code");
        }
    }//GEN-LAST:event_jLabel5MouseClicked
 
    private void sub_codeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sub_codeMouseClicked
        sub_code.setText(null);
    }//GEN-LAST:event_sub_codeMouseClicked

    /**
     * @param args the command line arguments
     */
    
    void showAtt(){
        boolean flag=false;
        atttble.setVisible(flag);
    }
    
    
    void showAtt2()
    {
        Student stu=new Student();
        try {
            Connection con=MyConnection.getConnection();
            String sql="select *from attendance where stu_id='"+stu.getRegno()+"'";
            PreparedStatement ps=con.prepareStatement(sql);
            ResultSet rs=ps.executeQuery();
            atttble.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            System.out.println(e);
        }
        
        
    }  
    
    void eligibility()
    {
        Eligibility ele=new Eligibility();
        
        String sub=sub_code.getText();
        String id=stu.getRegno();
        
        float t=ele.getTheoryEligibility(id, sub);
        String countTh=String.format("%f", t);
        
        float p=ele.getPracticalEligibility(id, sub);
        String countPra=String.format("%f", p);
        
        ele.getTotalEligibility(id,sub);
        
        attCount.setText(countTh);
        praCount.setText(countPra);
        
        att.setText(ele.getEligible(ele.getTheoryEligibility(id, sub)));
        pra.setText(ele.getEligible(ele.getPracticalEligibility(id, sub)));  
    }  
    
     void eligibility_TCS()
    {
        Eligibility ele=new Eligibility();
        
        String sub=sub_code.getText();
        String id=stu.getRegno();
        
        float t=ele.getTheoryEligibility(id, sub);
        String countTh=String.format("%f", t);
        
        ele.getTotalEligibility(id,sub);
        
        attCount.setText(countTh);
        praCount.setText("-");
        
        att.setText(ele.getEligible(ele.getTheoryEligibility(id, sub)));
        pra.setText("-");
  
    } 
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new attendance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel att;
    private javax.swing.JLabel attCount;
    private javax.swing.JTable atttble;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel pra;
    private javax.swing.JLabel praCount;
    private javax.swing.JPanel stuBar;
    private javax.swing.JTextField sub_code;
    private javax.swing.JLabel theory;
    // End of variables declaration//GEN-END:variables
}
