/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fot;

import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;



/**
 *
 * @author user
 */
public class Create_Profile extends javax.swing.JFrame {

    String stuFileName=null;
    byte[] stuImage=null;
    
    String lecFileName=null;
    byte[] lecImage=null;
    
    String tecFileName=null;
    byte[] tecImage=null;
    
    String admFileName=null;
    byte[] admImage=null;
    
    
    public Create_Profile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        Student = new javax.swing.JPanel();
        createStuId = new javax.swing.JLabel();
        createStuIdTxt = new javax.swing.JTextField();
        createDepId = new javax.swing.JLabel();
        createDepIdTxt = new javax.swing.JComboBox<>();
        createLecId = new javax.swing.JLabel();
        createLecIdTxt = new javax.swing.JComboBox<>();
        createStuName = new javax.swing.JLabel();
        createStuNameTxt = new javax.swing.JTextField();
        createStuAddressTxt = new javax.swing.JTextField();
        createStuAddress = new javax.swing.JLabel();
        createStuGender = new javax.swing.JLabel();
        createStuGenderTxt = new javax.swing.JComboBox<>();
        createStuBday = new javax.swing.JLabel();
        createStuPnoTxt = new javax.swing.JTextField();
        createStuPno = new javax.swing.JLabel();
        sumbit = new javax.swing.JButton();
        stuUpload = new javax.swing.JButton();
        createStuPwd = new javax.swing.JLabel();
        createStuPwdTxt = new javax.swing.JPasswordField();
        Exit = new javax.swing.JLabel();
        createStuBdayTxt = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        StudentProPic = new javax.swing.JLabel();
        stuShowPassword = new javax.swing.JCheckBox();
        back = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        createLecturerId = new javax.swing.JLabel();
        createLecturerIdTxt = new javax.swing.JTextField();
        createLecturerDepId = new javax.swing.JLabel();
        createLecturerDepIdTxt = new javax.swing.JComboBox<>();
        createLecturerName = new javax.swing.JLabel();
        createLecturerNameTxt = new javax.swing.JTextField();
        createLecturerAddress = new javax.swing.JLabel();
        createLecturerAddressTxt = new javax.swing.JTextField();
        createLecturerGender = new javax.swing.JLabel();
        createLecturerGenderTxt = new javax.swing.JComboBox<>();
        createLecturerPno = new javax.swing.JLabel();
        createLecturerPnoTxt = new javax.swing.JTextField();
        createLecturerPwd = new javax.swing.JLabel();
        createLecturerPwdTxt = new javax.swing.JPasswordField();
        LecturerSumbit = new javax.swing.JButton();
        LecturerUpload = new javax.swing.JButton();
        lecShowPassword = new javax.swing.JCheckBox();
        Exit1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        LecturerProPic = new javax.swing.JLabel();
        back1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        createTecId = new javax.swing.JLabel();
        createTecIdTxt = new javax.swing.JTextField();
        createTecDepId = new javax.swing.JLabel();
        createTecName = new javax.swing.JLabel();
        createTecNameTxt = new javax.swing.JTextField();
        createTecGender = new javax.swing.JLabel();
        createTecPno = new javax.swing.JLabel();
        createTecPnoTxt = new javax.swing.JTextField();
        createTecPwd = new javax.swing.JLabel();
        createTecPwdTxt = new javax.swing.JPasswordField();
        TecSumbit = new javax.swing.JButton();
        pic = new javax.swing.JPanel();
        TecnicalProPic = new javax.swing.JLabel();
        TecUpload = new javax.swing.JButton();
        Exit2 = new javax.swing.JLabel();
        createTecDepIdTxt = new javax.swing.JComboBox<>();
        createTecGenderTxt = new javax.swing.JComboBox<>();
        tecShowPassword = new javax.swing.JCheckBox();
        back2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Create Profile");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N

        Student.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        createStuId.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        createStuId.setForeground(new java.awt.Color(255, 255, 255));
        createStuId.setText("Student ID");
        Student.add(createStuId, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        createStuIdTxt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        createStuIdTxt.setText("tgxxx");
        Student.add(createStuIdTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 150, 30));

        createDepId.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        createDepId.setForeground(new java.awt.Color(255, 255, 255));
        createDepId.setText("Department ID");
        Student.add(createDepId, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        createDepIdTxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "depICT", "depENT" }));
        Student.add(createDepIdTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, -1, 30));

        createLecId.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        createLecId.setForeground(new java.awt.Color(255, 255, 255));
        createLecId.setText("Lecturer ID");
        Student.add(createLecId, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        createLecIdTxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "lec01", "lec02", "lec03" }));
        Student.add(createLecIdTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, -1, -1));

        createStuName.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        createStuName.setForeground(new java.awt.Color(255, 255, 255));
        createStuName.setText("Name");
        Student.add(createStuName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        createStuNameTxt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Student.add(createStuNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 150, 30));

        createStuAddressTxt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Student.add(createStuAddressTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 350, 30));

        createStuAddress.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        createStuAddress.setForeground(new java.awt.Color(255, 255, 255));
        createStuAddress.setText(" Address");
        Student.add(createStuAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        createStuGender.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        createStuGender.setForeground(new java.awt.Color(255, 255, 255));
        createStuGender.setText("Gender");
        Student.add(createStuGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, -1, -1));

        createStuGenderTxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));
        createStuGenderTxt.setVerifyInputWhenFocusTarget(false);
        Student.add(createStuGenderTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, -1, -1));

        createStuBday.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        createStuBday.setForeground(new java.awt.Color(255, 255, 255));
        createStuBday.setText("Birthday");
        Student.add(createStuBday, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, -1, -1));

        createStuPnoTxt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Student.add(createStuPnoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 530, 150, 30));

        createStuPno.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        createStuPno.setForeground(new java.awt.Color(255, 255, 255));
        createStuPno.setText("Phone Number");
        Student.add(createStuPno, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, -1, -1));

        sumbit.setText("Submit");
        sumbit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sumbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumbitActionPerformed(evt);
            }
        });
        Student.add(sumbit, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 560, -1, -1));

        stuUpload.setText("Upload");
        stuUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stuUploadActionPerformed(evt);
            }
        });
        Student.add(stuUpload, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 200, -1, -1));

        createStuPwd.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        createStuPwd.setForeground(new java.awt.Color(255, 255, 255));
        createStuPwd.setText("Password");
        Student.add(createStuPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 440, -1, -1));
        Student.add(createStuPwdTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 440, 150, 30));

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/exit.png"))); // NOI18N
        Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });
        Student.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 20, -1, -1));

        createStuBdayTxt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Student.add(createStuBdayTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, 150, 30));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        StudentProPic.setBackground(new java.awt.Color(255, 255, 0));
        StudentProPic.setForeground(new java.awt.Color(255, 255, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(StudentProPic, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(StudentProPic, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        Student.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 60, 120, 120));

        stuShowPassword.setBackground(new java.awt.Color(51, 51, 51));
        stuShowPassword.setForeground(new java.awt.Color(255, 255, 255));
        stuShowPassword.setText("Show Password");
        stuShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stuShowPasswordActionPerformed(evt);
            }
        });
        Student.add(stuShowPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 490, -1, -1));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/profBack.jpg"))); // NOI18N
        Student.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 620));

        jTabbedPane1.addTab("Student", Student);

        createLecturerId.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        createLecturerId.setForeground(new java.awt.Color(255, 255, 255));
        createLecturerId.setText("Lecturer ID");

        createLecturerIdTxt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        createLecturerIdTxt.setText("lecxx");

        createLecturerDepId.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        createLecturerDepId.setForeground(new java.awt.Color(255, 255, 255));
        createLecturerDepId.setText("Department ID");

        createLecturerDepIdTxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "depICT" }));

        createLecturerName.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        createLecturerName.setForeground(new java.awt.Color(255, 255, 255));
        createLecturerName.setText("Name");

        createLecturerNameTxt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        createLecturerAddress.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        createLecturerAddress.setForeground(new java.awt.Color(255, 255, 255));
        createLecturerAddress.setText(" Address");

        createLecturerAddressTxt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        createLecturerGender.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        createLecturerGender.setForeground(new java.awt.Color(255, 255, 255));
        createLecturerGender.setText("Gender");

        createLecturerGenderTxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));
        createLecturerGenderTxt.setVerifyInputWhenFocusTarget(false);

        createLecturerPno.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        createLecturerPno.setForeground(new java.awt.Color(255, 255, 255));
        createLecturerPno.setText("Phone Number");

        createLecturerPnoTxt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        createLecturerPwd.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        createLecturerPwd.setForeground(new java.awt.Color(255, 255, 255));
        createLecturerPwd.setText("Password");

        LecturerSumbit.setText("Submit");
        LecturerSumbit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LecturerSumbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LecturerSumbitActionPerformed(evt);
            }
        });

        LecturerUpload.setText("Upload");
        LecturerUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LecturerUploadActionPerformed(evt);
            }
        });

        lecShowPassword.setBackground(new java.awt.Color(51, 51, 51));
        lecShowPassword.setForeground(new java.awt.Color(255, 255, 255));
        lecShowPassword.setText("Show Password");
        lecShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lecShowPasswordActionPerformed(evt);
            }
        });

        Exit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/exit.png"))); // NOI18N
        Exit1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Exit1MouseClicked(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        LecturerProPic.setBackground(new java.awt.Color(255, 255, 0));
        LecturerProPic.setForeground(new java.awt.Color(255, 255, 0));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(LecturerProPic, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(LecturerProPic, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        back1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/profBack.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createLecturerName)
                    .addComponent(createLecturerId)
                    .addComponent(createLecturerAddress)
                    .addComponent(createLecturerGender)
                    .addComponent(createLecturerPno)
                    .addComponent(createLecturerPwd)
                    .addComponent(createLecturerDepId))
                .addGap(53, 53, 53)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(createLecturerIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(createLecturerAddressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(createLecturerPwdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(createLecturerGenderTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(createLecturerPnoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(260, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(Exit1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(createLecturerNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(createLecturerDepIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(41, 41, 41))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addComponent(lecShowPassword)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(LecturerUpload)
                        .addGap(69, 69, 69))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(LecturerSumbit)
                        .addGap(79, 79, 79))))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(back1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(createLecturerIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(createLecturerId))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(createLecturerDepIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(createLecturerDepId))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(createLecturerNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(createLecturerName)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Exit1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LecturerUpload)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createLecturerAddressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createLecturerAddress))
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createLecturerGender)
                    .addComponent(createLecturerGenderTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createLecturerPnoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createLecturerPno))
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createLecturerPwdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createLecturerPwd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lecShowPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addComponent(LecturerSumbit)
                .addGap(37, 37, 37))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(back1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Lecturer", jPanel2);

        createTecId.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        createTecId.setForeground(new java.awt.Color(255, 255, 255));
        createTecId.setText("Tecnical Officer ID");

        createTecIdTxt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        createTecIdTxt.setText("tecxx");

        createTecDepId.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        createTecDepId.setForeground(new java.awt.Color(255, 255, 255));
        createTecDepId.setText("Department ID");

        createTecName.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        createTecName.setForeground(new java.awt.Color(255, 255, 255));
        createTecName.setText("Name");

        createTecNameTxt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        createTecGender.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        createTecGender.setForeground(new java.awt.Color(255, 255, 255));
        createTecGender.setText("Gender");

        createTecPno.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        createTecPno.setForeground(new java.awt.Color(255, 255, 255));
        createTecPno.setText("Phone Number");

        createTecPnoTxt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        createTecPwd.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        createTecPwd.setForeground(new java.awt.Color(255, 255, 255));
        createTecPwd.setText("Password");

        TecSumbit.setText("Submit");
        TecSumbit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TecSumbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TecSumbitActionPerformed(evt);
            }
        });

        pic.setBackground(new java.awt.Color(255, 255, 255));

        TecnicalProPic.setBackground(new java.awt.Color(255, 255, 0));
        TecnicalProPic.setForeground(new java.awt.Color(255, 255, 0));

        javax.swing.GroupLayout picLayout = new javax.swing.GroupLayout(pic);
        pic.setLayout(picLayout);
        picLayout.setHorizontalGroup(
            picLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, picLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(TecnicalProPic, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        picLayout.setVerticalGroup(
            picLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, picLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(TecnicalProPic, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        TecUpload.setText("Upload");
        TecUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TecUploadActionPerformed(evt);
            }
        });

        Exit2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/exit.png"))); // NOI18N
        Exit2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exit2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Exit2MouseClicked(evt);
            }
        });

        createTecDepIdTxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "depICT", "depENT" }));

        createTecGenderTxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));
        createTecGenderTxt.setVerifyInputWhenFocusTarget(false);

        tecShowPassword.setBackground(new java.awt.Color(51, 51, 51));
        tecShowPassword.setForeground(new java.awt.Color(255, 255, 255));
        tecShowPassword.setText("Show Password");
        tecShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tecShowPasswordActionPerformed(evt);
            }
        });

        back2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/profBack.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(createTecPno)
                            .addComponent(createTecPwd)
                            .addComponent(createTecGender)
                            .addComponent(createTecName)
                            .addComponent(createTecDepId))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(createTecNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(createTecPnoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(createTecPwdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(createTecGenderTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 203, Short.MAX_VALUE)
                                .addComponent(pic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(107, 107, 107))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(TecUpload)
                                .addGap(134, 134, 134))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(createTecId)
                        .addGap(74, 74, 74)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(createTecDepIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(createTecIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Exit2)
                                .addGap(40, 40, 40))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TecSumbit)
                .addGap(64, 64, 64))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(253, 253, 253)
                .addComponent(tecShowPassword)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(back2)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createTecId)
                    .addComponent(createTecIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(createTecDepId)
                        .addGap(65, 65, 65)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(createTecNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(createTecName)))
                    .addComponent(createTecDepIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createTecGender)
                    .addComponent(createTecGenderTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createTecPnoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createTecPno))
                .addGap(53, 53, 53)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createTecPwdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createTecPwd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tecShowPassword)
                .addGap(0, 126, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(Exit2)
                .addGap(58, 58, 58)
                .addComponent(pic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TecUpload)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TecSumbit)
                .addGap(47, 47, 47))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(back2)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Technical Officer", jPanel3);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 650));
        jTabbedPane1.getAccessibleContext().setAccessibleName("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void sumbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumbitActionPerformed
        
        ProfileStudent p=new ProfileStudent();

        Object dId= createDepIdTxt.getSelectedItem();
        String depId=dId.toString();
        
        Object lId= createLecIdTxt.getSelectedItem();
        String lecId=lId.toString();
        
        Object gId= createStuGenderTxt.getSelectedItem();
        String genId=gId.toString();

        String stuId=createStuIdTxt.getText().trim();
        String stuName=createStuNameTxt.getText().trim();
        String stuAdd=createStuAddressTxt.getText().trim();
        String stuBday=createStuBdayTxt.getText().trim();
        String stuPno=createStuPnoTxt.getText().trim();
        String stuPwd=createStuPwdTxt.getText().trim();
        

        if(stuId.isEmpty() || stuName.isEmpty() || stuAdd.isEmpty() || stuBday.isEmpty() || stuPno.isEmpty() || stuPwd.isEmpty())
        {
            javax.swing.JOptionPane.showMessageDialog(null, "Please enter all fields!!!");
        }

        else
        {

            p.setProfileDepId(depId);
            p.setProfileLecId(lecId);
            p.setProfileGender(genId);
            p.setProfileStuId(createStuIdTxt.getText());
            p.setProfileStuName(createStuNameTxt.getText());
            p.setProfileStuAddress(createStuAddressTxt.getText());
            p.setProfileStuBday(createStuBdayTxt.getText());
            p.setProfileStuPno(createStuPnoTxt.getText());
            p.setProfileStuPwd(createStuPwdTxt.getText());
            p.setProfilePic(stuImage);

            p.createProfileStudent();

            clearProfileStudent();
        }
    }//GEN-LAST:event_sumbitActionPerformed

     public void clearProfileStudent()
    {
        createStuIdTxt.setText("tgxxx");
        createStuNameTxt.setText(null);
        createStuAddressTxt.setText(null);
        createStuBdayTxt.setText(null);
        createStuPnoTxt.setText(null);
        createStuPwdTxt.setText(null);
    } 
    
    private void stuUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stuUploadActionPerformed
       JFileChooser lecChooser= new JFileChooser();
        lecChooser.showOpenDialog(null);
        File stu=lecChooser.getSelectedFile();
        stuFileName=stu.getAbsolutePath();
        ImageIcon imageStu= new ImageIcon(new ImageIcon(stuFileName).getImage().getScaledInstance(StudentProPic.getWidth(), StudentProPic.getHeight(),Image.SCALE_SMOOTH));
        StudentProPic.setIcon(imageStu);
        
        try
        {
            File stuPic =new File(stuFileName);
            FileInputStream Sis= new FileInputStream(stuPic);
            ByteArrayOutputStream Sos= new ByteArrayOutputStream();
            byte[] buf=new byte[1024];
            
            for(int readNum;(readNum=Sis.read(buf))!=-1;)
            {
                Sos.write(buf,0,readNum);
            }
            stuImage=Sos.toByteArray();
        }
        catch(Exception e)
        {
             JOptionPane.showMessageDialog(null,e);
        }
        
    }//GEN-LAST:event_stuUploadActionPerformed

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        Admin_Profile p=new Admin_Profile();  // back to the user profiles
        p.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ExitMouseClicked

    private void LecturerSumbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LecturerSumbitActionPerformed
        
      ProfileLecturer p=new ProfileLecturer();
      
      Object LecgenId= createLecturerGenderTxt.getSelectedItem();
        String genId=LecgenId.toString();
        
        Object LecDep= createLecturerDepIdTxt.getSelectedItem();
        String depId=LecDep.toString();

        String lecId=createLecturerIdTxt.getText().trim();
        String lecName=createLecturerNameTxt.getText().trim();
        String lecAdd=createLecturerAddressTxt.getText().trim();
        String lecPno=createLecturerPnoTxt.getText().trim();
        String lecPwd=createLecturerPwdTxt.getText().trim();
        
        if(lecId.isEmpty() || lecName.isEmpty() || lecAdd.isEmpty() || lecPno.isEmpty() || lecPwd.isEmpty())
        {
            javax.swing.JOptionPane.showMessageDialog(null, "Please enter all fields!!!");
        }
        else
        {

            p.setProfileLecturerDepId(depId);
            p.setProfileLecturerGender(genId);
            p.setProfileLecturerId(createLecturerIdTxt.getText());
            p.setProfileLecturerName(createLecturerNameTxt.getText());
            p.setProfileLecturerAddress(createLecturerAddressTxt.getText());
            p.setProfileLecturerPno(createLecturerPnoTxt.getText());
            p.setProfileLecturerPwd(createLecturerPwdTxt.getText());
            p.setProfileLecturerPic(lecImage);

            p.createProfileLecturer();

            clearProfileLecturer();
            
        }
          
        
        
    }//GEN-LAST:event_LecturerSumbitActionPerformed

    public void clearProfileLecturer()
    {
        createLecturerIdTxt.setText(("lecxx"));
        createLecturerNameTxt.setText(null);
        createLecturerAddressTxt.setText(null);
        createLecturerPnoTxt.setText(null);
        createLecturerPwdTxt.setText(null);
    } 
    
    
    private void LecturerUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LecturerUploadActionPerformed
        JFileChooser lecChooser= new JFileChooser();
        lecChooser.showOpenDialog(null);
        File lec=lecChooser.getSelectedFile();
        lecFileName=lec.getAbsolutePath();
        ImageIcon imageLec= new ImageIcon(new ImageIcon(lecFileName).getImage().getScaledInstance(LecturerProPic.getWidth(), LecturerProPic.getHeight(),Image.SCALE_SMOOTH));
        LecturerProPic.setIcon(imageLec);
        
        try
        {
            File lecPic =new File(lecFileName);
            FileInputStream Lis= new FileInputStream(lecPic);
            ByteArrayOutputStream Los= new ByteArrayOutputStream();
            byte[] buf=new byte[1024];
            
            for(int readNum;(readNum=Lis.read(buf))!=-1;)
            {
                Los.write(buf,0,readNum);
            }
            lecImage=Los.toByteArray();
        }
        catch(Exception e)
        {
             JOptionPane.showMessageDialog(null,e);
        }
        
        
    }//GEN-LAST:event_LecturerUploadActionPerformed

    private void Exit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Exit1MouseClicked
        Admin_Profile p=new Admin_Profile();  // back to the user profiles
        p.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Exit1MouseClicked

    private void TecUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TecUploadActionPerformed
       JFileChooser tecChooser= new JFileChooser();
        tecChooser.showOpenDialog(null);
        File tec=tecChooser.getSelectedFile();
        tecFileName=tec.getAbsolutePath();
        ImageIcon imageTec= new ImageIcon(new ImageIcon(tecFileName).getImage().getScaledInstance(TecnicalProPic.getWidth(), TecnicalProPic.getHeight(),Image.SCALE_SMOOTH));
        TecnicalProPic.setIcon(imageTec);
        
        try
        {
            File tecPic =new File(tecFileName);
            FileInputStream Tis= new FileInputStream(tecPic);
            ByteArrayOutputStream Tos= new ByteArrayOutputStream();
            byte[] buf=new byte[1024];
            
            for(int readNum;(readNum=Tis.read(buf))!=-1;)
            {
                Tos.write(buf,0,readNum);
            }
            tecImage=Tos.toByteArray();
        }
        catch(Exception e)
        {
             JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_TecUploadActionPerformed

    private void TecSumbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TecSumbitActionPerformed
         ProfileTecnical p=new ProfileTecnical();

        Object dId= createTecDepIdTxt.getSelectedItem();
        String depId=dId.toString();
        
        
        Object gId= createTecGenderTxt.getSelectedItem();
        String genId=gId.toString();

        String tecId=createTecIdTxt.getText().trim();
        String tecName=createTecNameTxt.getText().trim();
        String tecPno=createTecPnoTxt.getText().trim();
        String tecPwd=createTecPwdTxt.getText().trim();
        

        if(tecId.isEmpty() || tecName.isEmpty() || tecPno.isEmpty() || tecPwd.isEmpty())
        {
            javax.swing.JOptionPane.showMessageDialog(null, "Please enter all fields!!!");
        }

        else
        {

            p.setProfileDepId(depId);
            p.setProfileGender(genId);
            p.setProfileId(createTecIdTxt.getText());
            p.setProfileName(createTecNameTxt.getText());
            p.setProfilePno(createTecPnoTxt.getText());
            p.setProfilePwd(createTecPwdTxt.getText());
            p.setProfilePic(tecImage);

           p.createProfileTecnical();

            clearProfileTo();
        } 
    }//GEN-LAST:event_TecSumbitActionPerformed

    public void clearProfileTo()
    {
        createTecIdTxt.setText(("tecxx"));
        createTecNameTxt.setText(null);
        createTecPnoTxt.setText(null);
        createTecPwdTxt.setText(null);
    } 
    
    private void Exit2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Exit2MouseClicked
        Admin_Profile p=new Admin_Profile();  // back to the user profiles
        p.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Exit2MouseClicked

    private void stuShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stuShowPasswordActionPerformed
        if(stuShowPassword.isSelected())
        {
            createStuPwdTxt.setEchoChar((char)0);
        }
        else
        {
             createStuPwdTxt.setEchoChar('●');
        }
    }//GEN-LAST:event_stuShowPasswordActionPerformed

    private void lecShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lecShowPasswordActionPerformed
        if(lecShowPassword.isSelected())
        {
            createLecturerPwdTxt.setEchoChar((char)0);
        }
        else
        {
             createLecturerPwdTxt.setEchoChar('●');
        }
    }//GEN-LAST:event_lecShowPasswordActionPerformed

    private void tecShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tecShowPasswordActionPerformed
       if(tecShowPassword.isSelected())
        {
            createTecPwdTxt.setEchoChar((char)0);
        }
        else
        {
             createTecPwdTxt.setEchoChar('●');
        }
    }//GEN-LAST:event_tecShowPasswordActionPerformed

       
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Create_Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Create_Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Create_Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Create_Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Create_Profile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Exit;
    private javax.swing.JLabel Exit1;
    private javax.swing.JLabel Exit2;
    private javax.swing.JLabel LecturerProPic;
    private javax.swing.JButton LecturerSumbit;
    private javax.swing.JButton LecturerUpload;
    private javax.swing.JPanel Student;
    private javax.swing.JLabel StudentProPic;
    private javax.swing.JButton TecSumbit;
    private javax.swing.JButton TecUpload;
    private javax.swing.JLabel TecnicalProPic;
    private javax.swing.JLabel back;
    private javax.swing.JLabel back1;
    private javax.swing.JLabel back2;
    private javax.swing.JLabel createDepId;
    private javax.swing.JComboBox<String> createDepIdTxt;
    private javax.swing.JLabel createLecId;
    private javax.swing.JComboBox<String> createLecIdTxt;
    private javax.swing.JLabel createLecturerAddress;
    private javax.swing.JTextField createLecturerAddressTxt;
    private javax.swing.JLabel createLecturerDepId;
    private javax.swing.JComboBox<String> createLecturerDepIdTxt;
    private javax.swing.JLabel createLecturerGender;
    private javax.swing.JComboBox<String> createLecturerGenderTxt;
    private javax.swing.JLabel createLecturerId;
    private javax.swing.JTextField createLecturerIdTxt;
    private javax.swing.JLabel createLecturerName;
    private javax.swing.JTextField createLecturerNameTxt;
    private javax.swing.JLabel createLecturerPno;
    private javax.swing.JTextField createLecturerPnoTxt;
    private javax.swing.JLabel createLecturerPwd;
    private javax.swing.JPasswordField createLecturerPwdTxt;
    private javax.swing.JLabel createStuAddress;
    private javax.swing.JTextField createStuAddressTxt;
    private javax.swing.JLabel createStuBday;
    private javax.swing.JTextField createStuBdayTxt;
    private javax.swing.JLabel createStuGender;
    private javax.swing.JComboBox<String> createStuGenderTxt;
    private javax.swing.JLabel createStuId;
    private javax.swing.JTextField createStuIdTxt;
    private javax.swing.JLabel createStuName;
    private javax.swing.JTextField createStuNameTxt;
    private javax.swing.JLabel createStuPno;
    private javax.swing.JTextField createStuPnoTxt;
    private javax.swing.JLabel createStuPwd;
    private javax.swing.JPasswordField createStuPwdTxt;
    private javax.swing.JLabel createTecDepId;
    private javax.swing.JComboBox<String> createTecDepIdTxt;
    private javax.swing.JLabel createTecGender;
    private javax.swing.JComboBox<String> createTecGenderTxt;
    private javax.swing.JLabel createTecId;
    private javax.swing.JTextField createTecIdTxt;
    private javax.swing.JLabel createTecName;
    private javax.swing.JTextField createTecNameTxt;
    private javax.swing.JLabel createTecPno;
    private javax.swing.JTextField createTecPnoTxt;
    private javax.swing.JLabel createTecPwd;
    private javax.swing.JPasswordField createTecPwdTxt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JCheckBox lecShowPassword;
    private javax.swing.JPanel pic;
    private javax.swing.JCheckBox stuShowPassword;
    private javax.swing.JButton stuUpload;
    private javax.swing.JButton sumbit;
    private javax.swing.JCheckBox tecShowPassword;
    // End of variables declaration//GEN-END:variables
}
