/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fot;

import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class Delete_Course extends javax.swing.JFrame {

    /**
     * Creates new form Delete_Course
     */
    public Delete_Course() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deleteSubID = new javax.swing.JLabel();
        deleteSubIdTxt = new javax.swing.JTextField();
        deleteSearch = new javax.swing.JLabel();
        deleteDepId = new javax.swing.JLabel();
        deleteDepIdTxt = new javax.swing.JTextField();
        deleteSubName = new javax.swing.JLabel();
        deleteSubNameTxt = new javax.swing.JTextField();
        deleteLecId = new javax.swing.JLabel();
        deleteLecIdTxt = new javax.swing.JTextField();
        Delete = new javax.swing.JButton();
        Exit = new javax.swing.JLabel();
        noticeBackImg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Delete Course");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        deleteSubID.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        deleteSubID.setForeground(new java.awt.Color(255, 255, 0));
        deleteSubID.setText("Enter Subject Code");
        getContentPane().add(deleteSubID, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        deleteSubIdTxt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        getContentPane().add(deleteSubIdTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 150, 25));

        deleteSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search.png"))); // NOI18N
        deleteSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteSearchMouseClicked(evt);
            }
        });
        getContentPane().add(deleteSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, 30, 30));

        deleteDepId.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        deleteDepId.setForeground(new java.awt.Color(255, 255, 255));
        deleteDepId.setText("Department ID");
        getContentPane().add(deleteDepId, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        deleteDepIdTxt.setEditable(false);
        deleteDepIdTxt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        getContentPane().add(deleteDepIdTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 150, 25));

        deleteSubName.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        deleteSubName.setForeground(new java.awt.Color(255, 255, 255));
        deleteSubName.setText("Subject Name");
        getContentPane().add(deleteSubName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        deleteSubNameTxt.setEditable(false);
        deleteSubNameTxt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        getContentPane().add(deleteSubNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 300, 30));

        deleteLecId.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        deleteLecId.setForeground(new java.awt.Color(255, 255, 255));
        deleteLecId.setText("Lecturer ID");
        getContentPane().add(deleteLecId, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));

        deleteLecIdTxt.setEditable(false);
        deleteLecIdTxt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        getContentPane().add(deleteLecIdTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 150, 25));

        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        getContentPane().add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 380, -1, -1));

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/exit.png"))); // NOI18N
        Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });
        getContentPane().add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, -1, -1));

        noticeBackImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/interface1.jpg"))); // NOI18N
        noticeBackImg.setPreferredSize(new java.awt.Dimension(600, 450));
        getContentPane().add(noticeBackImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 450));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void deleteSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteSearchMouseClicked
        String search=deleteSubIdTxt.getText();
        Course co=new Course();

        ResultSet rs=co.searchCourse(search);
        try {
            if(rs.next())
            {
                deleteDepIdTxt.setText(rs.getString("sub_dept_id"));
                deleteSubNameTxt.setText(rs.getString("sub_name"));
                deleteLecIdTxt.setText(rs.getString("lec_id"));
            }
            else
            {
                javax.swing.JOptionPane.showMessageDialog(null, "Data not in the database");
                clearCourse();
            }
        }
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null,"error....");
        }

    }//GEN-LAST:event_deleteSearchMouseClicked

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        Course co=new Course();

        co.setCourseDepId(deleteDepIdTxt.getText());
        co.setCourseSubId(deleteSubIdTxt.getText());
        co.setCourseSubName(deleteSubNameTxt.getText());
        co.setCourseLecId(deleteLecIdTxt.getText());

        co.deleteCourse();

        clearCourse();
    }//GEN-LAST:event_DeleteActionPerformed

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        Admin_Course co=new Admin_Course();  
        co.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ExitMouseClicked

     public void clearCourse()
    {
        deleteDepIdTxt.setText(null);
        deleteSubIdTxt.setText(null);
        deleteSubNameTxt.setText(null);
        deleteLecIdTxt.setText(null);
    }
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Delete_Course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Delete_Course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Delete_Course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Delete_Course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Delete_Course().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Delete;
    private javax.swing.JLabel Exit;
    private javax.swing.JLabel deleteDepId;
    private javax.swing.JTextField deleteDepIdTxt;
    private javax.swing.JLabel deleteLecId;
    private javax.swing.JTextField deleteLecIdTxt;
    private javax.swing.JLabel deleteSearch;
    private javax.swing.JLabel deleteSubID;
    private javax.swing.JTextField deleteSubIdTxt;
    private javax.swing.JLabel deleteSubName;
    private javax.swing.JTextField deleteSubNameTxt;
    private javax.swing.JLabel noticeBackImg;
    // End of variables declaration//GEN-END:variables
}
