/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fot;

import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class Delete_Notice extends javax.swing.JFrame {

    /**
     * Creates new form Edit_Notice
     */
    public Delete_Notice() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deleteNo = new javax.swing.JLabel();
        deleteNoTxt = new javax.swing.JTextField();
        deleteDate = new javax.swing.JLabel();
        deleteDateTxt = new javax.swing.JTextField();
        deleteTitle = new javax.swing.JLabel();
        deleteNotice = new javax.swing.JLabel();
        Delete = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        deleteNoticeTxt = new javax.swing.JTextArea();
        Exit = new javax.swing.JLabel();
        search = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        deleteTitleTxt = new javax.swing.JTextArea();
        noticeBack = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Delete Notice");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        deleteNo.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        deleteNo.setForeground(new java.awt.Color(255, 255, 0));
        deleteNo.setText("Enter Notice No");
        getContentPane().add(deleteNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        deleteNoTxt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        deleteNoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteNoTxtActionPerformed(evt);
            }
        });
        getContentPane().add(deleteNoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 150, 25));

        deleteDate.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        deleteDate.setForeground(new java.awt.Color(255, 255, 255));
        deleteDate.setText("Date");
        getContentPane().add(deleteDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        deleteDateTxt.setEditable(false);
        deleteDateTxt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        deleteDateTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteDateTxtActionPerformed(evt);
            }
        });
        getContentPane().add(deleteDateTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 150, 25));

        deleteTitle.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        deleteTitle.setForeground(new java.awt.Color(255, 255, 255));
        deleteTitle.setText("Title");
        getContentPane().add(deleteTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        deleteNotice.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        deleteNotice.setForeground(new java.awt.Color(255, 255, 255));
        deleteNotice.setText("Notice");
        getContentPane().add(deleteNotice, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        Delete.setText("Delete");
        Delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteMouseClicked(evt);
            }
        });
        getContentPane().add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 500, -1, -1));

        deleteNoticeTxt.setColumns(20);
        deleteNoticeTxt.setRows(5);
        jScrollPane2.setViewportView(deleteNoticeTxt);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 670, 130));

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/exit.png"))); // NOI18N
        Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });
        getContentPane().add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, -1, -1));

        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search.png"))); // NOI18N
        search.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchMouseClicked(evt);
            }
        });
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 30, 30));

        deleteTitleTxt.setColumns(20);
        deleteTitleTxt.setRows(5);
        jScrollPane1.setViewportView(deleteTitleTxt);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 670, -1));

        noticeBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/interface1.jpg"))); // NOI18N
        getContentPane().add(noticeBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void deleteNoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteNoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteNoTxtActionPerformed

    private void deleteDateTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteDateTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteDateTxtActionPerformed

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        Admin_Notice aNotice=new Admin_Notice();  // back to the user profiles
        aNotice.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ExitMouseClicked

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
           
    }//GEN-LAST:event_deleteActionPerformed

    private void searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseClicked
           String search=deleteNoTxt.getText();
        Notice no=new Notice();
        
        ResultSet rs=no.searchNotice(search);
        try {
            if(rs.next())
            {
           
               deleteDateTxt.setText(rs.getString("date"));
               deleteTitleTxt.setText(rs.getString("title"));
               deleteNoticeTxt.setText(rs.getString("notice"));       
            }
            else
            {
                 javax.swing.JOptionPane.showMessageDialog(null, "Data not in the database");
                  clearNotice();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,"error....");
        }

    }//GEN-LAST:event_searchMouseClicked

    private void DeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteMouseClicked
         
       Notice no=new Notice();
       
       no.setNoticeNo(deleteNoTxt.getText());
       no.setNoticeDate(deleteDateTxt.getText());
       no.setNoticeTitle(deleteTitleTxt.getText());
       no.setNoticeNotice(deleteNoticeTxt.getText());
       no.deleteNotice();   
       
        clearNotice();
    }//GEN-LAST:event_DeleteMouseClicked

        public void clearNotice()
    {
        deleteNoTxt.setText(null);
        deleteDateTxt.setText(null);
        deleteTitleTxt.setText(null);
        deleteNoticeTxt.setText(null);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Delete_Notice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Delete_Notice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Delete_Notice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Delete_Notice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Delete_Notice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Delete;
    private javax.swing.JLabel Exit;
    private javax.swing.JLabel deleteDate;
    private javax.swing.JTextField deleteDateTxt;
    private javax.swing.JLabel deleteNo;
    private javax.swing.JTextField deleteNoTxt;
    private javax.swing.JLabel deleteNotice;
    private javax.swing.JTextArea deleteNoticeTxt;
    private javax.swing.JLabel deleteTitle;
    private javax.swing.JTextArea deleteTitleTxt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel noticeBack;
    private javax.swing.JLabel search;
    // End of variables declaration//GEN-END:variables
}
