/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fot;

import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class Edit_Notice extends javax.swing.JFrame {

    /**
     * Creates new form Edit_Notice
     */
    public Edit_Notice() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editNo = new javax.swing.JLabel();
        editNoTxt = new javax.swing.JTextField();
        editDate = new javax.swing.JLabel();
        editDateTxt = new javax.swing.JTextField();
        editTitle = new javax.swing.JLabel();
        editNotice = new javax.swing.JLabel();
        update = new javax.swing.JButton();
        Exit = new javax.swing.JLabel();
        editSearch = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        editNoticeTxt = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        editTitleTxt = new javax.swing.JTextArea();
        noticeBack = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Edit Notice");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        editNo.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        editNo.setForeground(new java.awt.Color(255, 255, 0));
        editNo.setText("Enter Notice No");
        getContentPane().add(editNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        editNoTxt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        getContentPane().add(editNoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 150, 25));

        editDate.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        editDate.setForeground(new java.awt.Color(255, 255, 255));
        editDate.setText("Date");
        getContentPane().add(editDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        editDateTxt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        editDateTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editDateTxtActionPerformed(evt);
            }
        });
        getContentPane().add(editDateTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 150, 25));

        editTitle.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        editTitle.setForeground(new java.awt.Color(255, 255, 255));
        editTitle.setText("Title");
        getContentPane().add(editTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        editNotice.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        editNotice.setForeground(new java.awt.Color(255, 255, 255));
        editNotice.setText("Notice");
        getContentPane().add(editNotice, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        update.setText("Update");
        update.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateMouseClicked(evt);
            }
        });
        getContentPane().add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 500, -1, -1));

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/exit.png"))); // NOI18N
        Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });
        getContentPane().add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, -1, -1));

        editSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search.png"))); // NOI18N
        editSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editSearchMouseClicked(evt);
            }
        });
        getContentPane().add(editSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 30, 30));

        editNoticeTxt.setColumns(20);
        editNoticeTxt.setRows(5);
        jScrollPane2.setViewportView(editNoticeTxt);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 660, 140));

        editTitleTxt.setColumns(20);
        editTitleTxt.setRows(5);
        jScrollPane1.setViewportView(editTitleTxt);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 660, 70));

        noticeBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/interface1.jpg"))); // NOI18N
        getContentPane().add(noticeBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void deleteNoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteNoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteNoTxtActionPerformed

    private void deleteDateTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteDateTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteDateTxtActionPerformed

    private void deleteTitleTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteTitleTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteTitleTxtActionPerformed

    private void deleteNoticeTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteNoticeTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteNoticeTxtActionPerformed

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        Admin_Notice aNotice=new Admin_Notice();  // back to the user profiles
        aNotice.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ExitMouseClicked

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
     
    }//GEN-LAST:event_deleteActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
          

    }//GEN-LAST:event_jLabel1MouseClicked

    private void editSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editSearchMouseClicked
        String search=editNoTxt.getText();
        Notice no=new Notice();
        
        ResultSet rs=no.searchNotice(search);
        try {
            if(rs.next())
            {
           
               editDateTxt.setText(rs.getString("date"));
               editTitleTxt.setText(rs.getString("title"));
               editNoticeTxt.setText(rs.getString("notice"));  
            }
            else
            {
                 javax.swing.JOptionPane.showMessageDialog(null, "Data not in the database");
                 clearNotice();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,"error....");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_editSearchMouseClicked

    private void updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseClicked
        Notice no=new Notice();
       
       no.setNoticeNo(editNoTxt.getText());
       no.setNoticeDate(editDateTxt.getText());
       no.setNoticeTitle(editTitleTxt.getText());
       no.setNoticeNotice(editNoticeTxt.getText());
       no.editNotice();
       
      clearNotice();
    }//GEN-LAST:event_updateMouseClicked

    private void editDateTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editDateTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editDateTxtActionPerformed

    
    public void clearNotice()
    {
        editNoTxt.setText(null);
        editDateTxt.setText(null);
        editTitleTxt.setText(null);
        editNoticeTxt.setText(null);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Edit_Notice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Edit_Notice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Edit_Notice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Edit_Notice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Edit_Notice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Exit;
    private javax.swing.JLabel editDate;
    private javax.swing.JTextField editDateTxt;
    private javax.swing.JLabel editNo;
    private javax.swing.JTextField editNoTxt;
    private javax.swing.JLabel editNotice;
    private javax.swing.JTextArea editNoticeTxt;
    private javax.swing.JLabel editSearch;
    private javax.swing.JLabel editTitle;
    private javax.swing.JTextArea editTitleTxt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel noticeBack;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables

    
}
