/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package fot;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author user
 */
public class Edit_Timetable extends javax.swing.JFrame {

  
    public Edit_Timetable() {
        initComponents();
     
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        time = new javax.swing.JLabel();
        monTxt = new javax.swing.JTextField();
        mon = new javax.swing.JLabel();
        timeTxt = new javax.swing.JTextField();
        thuTxt = new javax.swing.JTextField();
        tueTxt = new javax.swing.JTextField();
        tue = new javax.swing.JLabel();
        friTxt = new javax.swing.JTextField();
        wedTxt = new javax.swing.JTextField();
        thu = new javax.swing.JLabel();
        wed1 = new javax.swing.JLabel();
        fri = new javax.swing.JLabel();
        edit = new javax.swing.JButton();
        Exit = new javax.swing.JLabel();
        noticeName = new javax.swing.JLabel();
        nameTxt = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Update Timetable");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Time", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday"
            }
        ));
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 396, 595, 156));

        time.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        time.setForeground(new java.awt.Color(255, 255, 255));
        time.setText("Time");
        getContentPane().add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 131, -1, -1));

        monTxt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        monTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monTxtActionPerformed(evt);
            }
        });
        getContentPane().add(monTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 166, 150, 30));

        mon.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        mon.setForeground(new java.awt.Color(255, 255, 255));
        mon.setText("Monday");
        getContentPane().add(mon, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, -1, -1));

        timeTxt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        timeTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeTxtActionPerformed(evt);
            }
        });
        getContentPane().add(timeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 166, 150, 30));

        thuTxt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        getContentPane().add(thuTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 255, 150, 30));

        tueTxt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        getContentPane().add(tueTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(504, 166, 150, 30));

        tue.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        tue.setForeground(new java.awt.Color(255, 255, 255));
        tue.setText("Tuesday");
        getContentPane().add(tue, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 130, -1, -1));

        friTxt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        getContentPane().add(friTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(504, 255, 150, 30));

        wedTxt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        getContentPane().add(wedTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 255, 150, 30));

        thu.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        thu.setForeground(new java.awt.Color(255, 255, 255));
        thu.setText("Thursday");
        getContentPane().add(thu, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 227, -1, -1));

        wed1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        wed1.setForeground(new java.awt.Color(255, 255, 255));
        wed1.setText("Wednesday");
        getContentPane().add(wed1, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 227, -1, -1));

        fri.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        fri.setForeground(new java.awt.Color(255, 255, 255));
        fri.setText("Friday");
        getContentPane().add(fri, new org.netbeans.lib.awtextra.AbsoluteConstraints(551, 227, -1, -1));

        edit.setText("Update");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        getContentPane().add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(576, 317, 70, 30));

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/exit.png"))); // NOI18N
        Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });
        getContentPane().add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(604, 30, -1, -1));

        noticeName.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        noticeName.setForeground(new java.awt.Color(255, 255, 255));
        noticeName.setText("Year");
        getContentPane().add(noticeName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        nameTxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Level_I", "Level_II", "Level_III", "Level_IV", " " }));
        nameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTxtActionPerformed(evt);
            }
        });
        getContentPane().add(nameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/profBack.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        Admin_TimeTable tm=new Admin_TimeTable();  
        tm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ExitMouseClicked

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
       
       Timetable_table tm=new Timetable_table();
         
       tm.setName(nameTxt.getSelectedItem().toString());
       tm.setTime(timeTxt.getText());
       tm.setMon(monTxt.getText());
       tm.setTue(tueTxt.getText());
       tm.setWed(wedTxt.getText());
       tm.setThu(thuTxt.getText());
       tm.setFri(friTxt.getText());
            
        tm.editTime();
        
            timeTxt.setText(null);
            monTxt.setText(null);
            tueTxt.setText(null);
            wedTxt.setText(null);
            thuTxt.setText(null);
            friTxt.setText(null);
            
         
        String name=nameTxt.getSelectedItem().toString();

        if(name.equals("Level_I"))
        {
            try {
                Connection con=MyConnection.getConnection();
                String sql="SELECT `time` AS 'Time', `mon` AS 'Monday', `tue` AS 'Tuesday', `wed` AS 'Wednesday', `thu` AS 'Thursday', `fri` AS 'Friday' FROM ict_level_i";
                PreparedStatement pst=con.prepareStatement(sql);
                ResultSet rs=pst.executeQuery();
                table.setModel(DbUtils.resultSetToTableModel(rs));
                table.setVisible(true);
            }
            catch (Exception e)
            {
                JOptionPane.showMessageDialog(null,e);
                table.setVisible(false);
            }
        }

        if(name.equals("Level_II"))
        {
            try {
                Connection con=MyConnection.getConnection();
                String sql="SELECT `time` AS 'Time', `mon` AS 'Monday', `tue` AS 'Tuesday', `wed` AS 'Wednesday', `thu` AS 'Thursday', `fri` AS 'Friday' FROM ict_level_i";
                PreparedStatement pst=con.prepareStatement(sql);
                ResultSet rs=pst.executeQuery();
                table.setModel(DbUtils.resultSetToTableModel(rs));
                table.setVisible(true);
            }
            catch (Exception e)
            {
                JOptionPane.showMessageDialog(null,e);
                table.setVisible(false);
            }
        }

        if(name.equals("Level_III"))
        {
            try {
                Connection con=MyConnection.getConnection();
                String sql="SELECT `time` AS 'Time', `mon` AS 'Monday', `tue` AS 'Tuesday', `wed` AS 'Wednesday', `thu` AS 'Thursday', `fri` AS 'Friday' FROM ict_level_i";
                PreparedStatement pst=con.prepareStatement(sql);
                ResultSet rs=pst.executeQuery();
                table.setModel(DbUtils.resultSetToTableModel(rs));
                table.setVisible(true);
            }
            catch (Exception e)
            {
                //JOptionPane.showMessageDialog(null,e);
                table.setVisible(false);
            }
        }

        if(name.equals("Level_IV"))
        {
            try {
                Connection con=MyConnection.getConnection();
               String sql="SELECT `time` AS 'Time', `mon` AS 'Monday', `tue` AS 'Tuesday', `wed` AS 'Wednesday', `thu` AS 'Thursday', `fri` AS 'Friday' FROM ict_level_i";
                 PreparedStatement pst=con.prepareStatement(sql);
                ResultSet rs=pst.executeQuery();
                table.setModel(DbUtils.resultSetToTableModel(rs));
                table.setVisible(true);
            }
            catch (Exception e)
            {
                //JOptionPane.showMessageDialog(null,e);
                table.setVisible(false);
            }
        }
       
       
    }//GEN-LAST:event_editActionPerformed

    private void nameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTxtActionPerformed

        String name=nameTxt.getSelectedItem().toString();

        if(name.equals("Level_I"))
        {
            try {
                Connection con=MyConnection.getConnection();
                String sql="select * from ict_level_i";
                PreparedStatement pst=con.prepareStatement(sql);
                ResultSet rs=pst.executeQuery();
                table.setModel(DbUtils.resultSetToTableModel(rs));
                table.setVisible(true);
            }
            catch (Exception e)
            {
                JOptionPane.showMessageDialog(null,e);
                table.setVisible(false);
            }
        }

        if(name.equals("Level_II"))
        {
            try {
                Connection con=MyConnection.getConnection();
                String sql="select * from ict_level_ii";
                PreparedStatement pst=con.prepareStatement(sql);
                ResultSet rs=pst.executeQuery();
                table.setModel(DbUtils.resultSetToTableModel(rs));
                table.setVisible(true);
            }
            catch (Exception e)
            {
                JOptionPane.showMessageDialog(null,e);
                table.setVisible(false);
            }
        }

        if(name.equals("Level_III"))
        {
            try {
                Connection con=MyConnection.getConnection();
                String sql="select * from ict_level_iii";
                PreparedStatement pst=con.prepareStatement(sql);
                ResultSet rs=pst.executeQuery();
                table.setModel(DbUtils.resultSetToTableModel(rs));
                table.setVisible(true);
            }
            catch (Exception e)
            {
                //JOptionPane.showMessageDialog(null,e);
                table.setVisible(false);
            }
        }

        if(name.equals("Level_IV"))
        {
            try {
                Connection con=MyConnection.getConnection();
                String sql="select * from ict_level_iv";
                PreparedStatement pst=con.prepareStatement(sql);
                ResultSet rs=pst.executeQuery();
                table.setModel(DbUtils.resultSetToTableModel(rs));
                table.setVisible(true);
            }
            catch (Exception e)
            {
                //JOptionPane.showMessageDialog(null,e);
                table.setVisible(false);
            }
        }
    }//GEN-LAST:event_nameTxtActionPerformed

    private void timeTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeTxtActionPerformed

    private void monTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monTxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Edit_Timetable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Edit_Timetable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Edit_Timetable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Edit_Timetable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Edit_Timetable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Exit;
    private javax.swing.JButton edit;
    private javax.swing.JLabel fri;
    private javax.swing.JTextField friTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mon;
    private javax.swing.JTextField monTxt;
    private javax.swing.JComboBox<String> nameTxt;
    private javax.swing.JLabel noticeName;
    private javax.swing.JTable table;
    private javax.swing.JLabel thu;
    private javax.swing.JTextField thuTxt;
    private javax.swing.JLabel time;
    private javax.swing.JTextField timeTxt;
    private javax.swing.JLabel tue;
    private javax.swing.JTextField tueTxt;
    private javax.swing.JLabel wed1;
    private javax.swing.JTextField wedTxt;
    // End of variables declaration//GEN-END:variables

}
