/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fot;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author user
 */
public class form_TO extends javax.swing.JFrame {

    /**
     * Creates new form form_TO
     */
    public form_TO() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tecImg = new javax.swing.JLabel();
        tecName = new javax.swing.JLabel();
        tecSubmit = new javax.swing.JButton();
        tecTxt = new javax.swing.JTextField();
        tecClear = new javax.swing.JButton();
        tecPwd = new javax.swing.JLabel();
        errMsg = new javax.swing.JLabel();
        tecLabel = new javax.swing.JLabel();
        tecExit = new javax.swing.JLabel();
        tecPwdTxt = new javax.swing.JPasswordField();
        stuBar = new javax.swing.JPanel();
        tecBack = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TO Interface");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tecImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/to.png"))); // NOI18N
        getContentPane().add(tecImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 120, 130));

        tecName.setBackground(new java.awt.Color(255, 255, 255));
        tecName.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        tecName.setForeground(new java.awt.Color(255, 255, 255));
        tecName.setText("User Name");
        getContentPane().add(tecName, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 120, 30));

        tecSubmit.setText("Login");
        tecSubmit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tecSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tecSubmitActionPerformed(evt);
            }
        });
        getContentPane().add(tecSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, -1, -1));

        tecTxt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        tecTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tecTxtActionPerformed(evt);
            }
        });
        getContentPane().add(tecTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 150, 25));

        tecClear.setText("Clear");
        tecClear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tecClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tecClearActionPerformed(evt);
            }
        });
        getContentPane().add(tecClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, -1, -1));

        tecPwd.setBackground(new java.awt.Color(255, 255, 255));
        tecPwd.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        tecPwd.setForeground(new java.awt.Color(255, 255, 255));
        tecPwd.setText("Password");
        getContentPane().add(tecPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 120, 30));
        getContentPane().add(errMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 150, 20));

        tecLabel.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        tecLabel.setForeground(new java.awt.Color(255, 255, 0));
        tecLabel.setText("TECNICAL OFFICER");
        getContentPane().add(tecLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        tecExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/exit.png"))); // NOI18N
        tecExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tecExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tecExitMouseClicked(evt);
            }
        });
        getContentPane().add(tecExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, -1, -1));

        tecPwdTxt.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        tecPwdTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tecPwdTxtActionPerformed(evt);
            }
        });
        getContentPane().add(tecPwdTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 150, 25));

        stuBar.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout stuBarLayout = new javax.swing.GroupLayout(stuBar);
        stuBar.setLayout(stuBarLayout);
        stuBarLayout.setHorizontalGroup(
            stuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        stuBarLayout.setVerticalGroup(
            stuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );

        getContentPane().add(stuBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 5, 260));

        tecBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/interface1.jpg"))); // NOI18N
        getContentPane().add(tecBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 300));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tecTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tecTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tecTxtActionPerformed

    private void tecPwdTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tecPwdTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tecPwdTxtActionPerformed

    private void tecExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tecExitMouseClicked
        forms_Login log=new forms_Login();  // back to the user profiles
        log.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_tecExitMouseClicked

    private void tecClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tecClearActionPerformed
        tecTxt.setText(null);
        tecPwdTxt.setText(null);
    }//GEN-LAST:event_tecClearActionPerformed

    private void tecSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tecSubmitActionPerformed
        String password=tecPwdTxt.getText().trim();
        String user_name=tecTxt.getText().trim();

        if(user_name.isEmpty() && password.isEmpty())
        {
            errMsg.setText("Please enter both fields!!!");
        }
        else if(password.isEmpty())
        {
            errMsg.setText("Please enter password!!!");
        }
        else if(user_name.isEmpty())
        {
            errMsg.setText("Please enter user name!!!");
        }
        else{
            ResultSet rs=null;
            try{
                Connection con=MyConnection.getConnection();
                String sql="call toLogin('"+user_name+"','"+password+"')";
                PreparedStatement ps=con.prepareStatement(sql);
                rs=ps.executeQuery();
                if(rs.next()==true)
                {
                    LogTO log=new LogTO();
                    log.setId(rs.getString("user_id"));

                    Tecnical_officer inter=new Tecnical_officer();
                    inter.setVisible(true);
                    this.setVisible(false);
                }
                else{
                    errMsg.setText("invalid user");
                }

            }
            catch(Exception e)
            {
                errMsg.setText("system error");
            }
        }
    }//GEN-LAST:event_tecSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_TO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_TO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_TO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_TO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_TO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel errMsg;
    private javax.swing.JPanel stuBar;
    private javax.swing.JLabel tecBack;
    private javax.swing.JButton tecClear;
    private javax.swing.JLabel tecExit;
    private javax.swing.JLabel tecImg;
    private javax.swing.JLabel tecLabel;
    private javax.swing.JLabel tecName;
    private javax.swing.JLabel tecPwd;
    private javax.swing.JPasswordField tecPwdTxt;
    private javax.swing.JButton tecSubmit;
    private javax.swing.JTextField tecTxt;
    // End of variables declaration//GEN-END:variables
}
