package fot;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MINHA
 */
public class Mark extends javax.swing.JFrame {
            Connection con=null;
            ResultSet rs=null;
            PreparedStatement pst;
    /**
     * Creates new form Attendance
     */
    public  Mark() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        subIdTxt = new javax.swing.JTextField();
        stuIdTxt = new javax.swing.JTextField();
        subId = new javax.swing.JLabel();
        stuId = new javax.swing.JLabel();
        qu1 = new javax.swing.JLabel();
        q1 = new javax.swing.JTextField();
        qu2 = new javax.swing.JLabel();
        Exit = new javax.swing.JLabel();
        q2 = new javax.swing.JTextField();
        qu3 = new javax.swing.JLabel();
        qu4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        q3 = new javax.swing.JTextField();
        q4 = new javax.swing.JTextField();
        as1 = new javax.swing.JLabel();
        as2 = new javax.swing.JLabel();
        a1 = new javax.swing.JTextField();
        as3 = new javax.swing.JLabel();
        a2 = new javax.swing.JTextField();
        mid = new javax.swing.JLabel();
        a3 = new javax.swing.JTextField();
        m1 = new javax.swing.JTextField();
        t = new javax.swing.JLabel();
        th = new javax.swing.JTextField();
        pr = new javax.swing.JTextField();
        p = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Marks");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        subIdTxt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        getContentPane().add(subIdTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 150, 30));

        stuIdTxt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        getContentPane().add(stuIdTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 150, -1));

        subId.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        subId.setForeground(new java.awt.Color(255, 255, 255));
        subId.setText("Subject ID");
        getContentPane().add(subId, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        stuId.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        stuId.setForeground(new java.awt.Color(255, 255, 255));
        stuId.setText("Student ID");
        getContentPane().add(stuId, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        qu1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        qu1.setForeground(new java.awt.Color(255, 255, 255));
        qu1.setText("Quiz 1");
        getContentPane().add(qu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        q1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        q1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q1ActionPerformed(evt);
            }
        });
        getContentPane().add(q1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 60, 30));

        qu2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        qu2.setForeground(new java.awt.Color(255, 255, 255));
        qu2.setText("Quiz 2");
        getContentPane().add(qu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, -1));

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/exit.png"))); // NOI18N
        Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });
        getContentPane().add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, -1, -1));

        q2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        getContentPane().add(q2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 60, -1));

        qu3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        qu3.setForeground(new java.awt.Color(255, 255, 255));
        qu3.setText("Quiz 3");
        getContentPane().add(qu3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 50, -1));

        qu4.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        qu4.setForeground(new java.awt.Color(255, 255, 255));
        qu4.setText("Quiz 4");
        getContentPane().add(qu4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, -1, -1));

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 423, 80, 30));

        q3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        getContentPane().add(q3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 60, -1));

        q4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        getContentPane().add(q4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 60, -1));

        as1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        as1.setForeground(new java.awt.Color(255, 255, 255));
        as1.setText("Assessment 1");
        getContentPane().add(as1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        as2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        as2.setForeground(new java.awt.Color(255, 255, 255));
        as2.setText("Assessment 2");
        getContentPane().add(as2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, -1, -1));

        a1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        getContentPane().add(a1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 60, 30));

        as3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        as3.setForeground(new java.awt.Color(255, 255, 255));
        as3.setText("Assessment 3");
        getContentPane().add(as3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, -1, -1));

        a2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        getContentPane().add(a2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 60, 30));

        mid.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        mid.setForeground(new java.awt.Color(255, 255, 255));
        mid.setText("Mid Exam");
        getContentPane().add(mid, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, -1, -1));

        a3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        getContentPane().add(a3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 60, 30));

        m1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        getContentPane().add(m1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, 60, 30));

        t.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        t.setForeground(new java.awt.Color(255, 255, 255));
        t.setText("Theory");
        getContentPane().add(t, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, -1, -1));

        th.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        getContentPane().add(th, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, 60, 30));

        pr.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        getContentPane().add(pr, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 310, 60, 30));

        p.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        p.setForeground(new java.awt.Color(255, 255, 255));
        p.setText("Practical");
        getContentPane().add(p, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/interface1.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setPreferredSize(new java.awt.Dimension(600, 500));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        Lec_Mark lec=new Lec_Mark();  
        lec.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ExitMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        MarkFile m=new MarkFile();


        String id=stuIdTxt.getText().trim();
        String sub=subIdTxt.getText().trim();

        if(!sub.equals("") && !id.equals("")){
            try {
                m.setId(stuIdTxt.getText());
                m.setSub(subIdTxt.getText());
                m.setQ1(q1.getText());
                m.setQ2(q2.getText());
                m.setQ3(q3.getText());
                m.setQ4(q4.getText());
                m.setA1(a1.getText());
                m.setA2(a2.getText());
                m.setA3(a3.getText());
                m.setMid(m1.getText());
                m.setTh(th.getText());
                m.setPr(pr.getText());

                m.create();
                clear();
            } 
            catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(null, e);
            }
        }
          else
          {
              javax.swing.JOptionPane.showMessageDialog(null, "Please enter Student ID and Subject ID ");
           }
        
        
            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void q1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q1ActionPerformed
 public void clear(){
        stuIdTxt.setText("");
        subIdTxt.setText("");
        q1.setText("");
        q2.setText("");
        q3.setText("");
        q4.setText("");
        a1.setText("");
        a2.setText("");
        a3.setText("");
        m1.setText("");
        th.setText("");
        pr.setText("");
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mark.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
      //</editor-fold>
      //</editor-fold>
      
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new  Mark().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Exit;
    private javax.swing.JTextField a1;
    private javax.swing.JTextField a2;
    private javax.swing.JTextField a3;
    private javax.swing.JLabel as1;
    private javax.swing.JLabel as2;
    private javax.swing.JLabel as3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField m1;
    private javax.swing.JLabel mid;
    private javax.swing.JLabel p;
    private javax.swing.JTextField pr;
    private javax.swing.JTextField q1;
    private javax.swing.JTextField q2;
    private javax.swing.JTextField q3;
    private javax.swing.JTextField q4;
    private javax.swing.JLabel qu1;
    private javax.swing.JLabel qu2;
    private javax.swing.JLabel qu3;
    private javax.swing.JLabel qu4;
    private javax.swing.JLabel stuId;
    private javax.swing.JTextField stuIdTxt;
    private javax.swing.JLabel subId;
    private javax.swing.JTextField subIdTxt;
    private javax.swing.JLabel t;
    private javax.swing.JTextField th;
    // End of variables declaration//GEN-END:variables
}
