/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package fot;

import java.sql.ResultSet;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Ishanka
 */
public class Notices extends javax.swing.JFrame {

    /** Creates new form Notices */
    public Notices() {
        initComponents();
        showData();
    }
    void showData()
    {
        Student stu=new Student();
        ResultSet result=stu.seeNotices();
        notice.setModel(DbUtils.resultSetToTableModel(result));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewdate = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        notice = new javax.swing.JTable();
        date = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        noticepic = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        viewtitle = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        viewnotice = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("View Notices");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        viewdate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        viewdate.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(viewdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 110, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("See Notices ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, -1, -1));

        notice.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Notice no", "Date", "Title", "Notice"
            }
        ));
        notice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                noticeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(notice);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 610, 150));

        date.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        date.setForeground(new java.awt.Color(255, 255, 255));
        date.setText("Date :");
        getContentPane().add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 60, 20));

        title.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("Title:");
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 60, 20));

        noticepic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/notice1.png"))); // NOI18N
        noticepic.setText("jLabel3");
        getContentPane().add(noticepic, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 120, 130));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Notice :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, -1, -1));

        viewtitle.setColumns(20);
        viewtitle.setRows(5);
        jScrollPane2.setViewportView(viewtitle);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 550, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/exit.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, 30, 30));

        viewnotice.setColumns(20);
        viewnotice.setRows(5);
        jScrollPane3.setViewportView(viewnotice);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, 550, 150));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/profBack.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 610));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void noticeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noticeMouseClicked
        int r=notice.getSelectedRow();
        
        String date=notice.getValueAt(r,1).toString();
        String title=notice.getValueAt(r,2).toString();
        String content=notice.getValueAt(r,3).toString();
        viewdate.setText(date);
        viewtitle.setText(title);
        viewnotice.setText(content);
        
        
    }//GEN-LAST:event_noticeMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
         Lecturer lec=new Lecturer();
         lec.setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Notices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Notices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Notices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Notices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Notices().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel date;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable notice;
    private javax.swing.JLabel noticepic;
    private javax.swing.JLabel title;
    private javax.swing.JLabel viewdate;
    private javax.swing.JTextArea viewnotice;
    private javax.swing.JTextArea viewtitle;
    // End of variables declaration//GEN-END:variables

}
